import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";
import "./globals.css";
import ConfigProviders from "@/context/config-provider";

const vazirmatn = Vazirmatn({
  variable: "--font-vazirmatn",
  subsets: ["latin"],
  weight: ["100","200", "300","400","500","600","700","800","900"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${vazirmatn.variable} antialiased`}
      >
        <ConfigProviders>{children}</ConfigProviders>
      </body>
    </html>
  );
}
